WebApplication3/Controllers/AppController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WebApplication3.Data;

namespace WebApplication3.Controllers
{
  public class AppController : Controller
  {
    private readonly ITvShowRepository repository;

    public AppController(ITvShowRepository repository)
    {
      this.repository = repository;
    }

    public IActionResult Index()
    {
      return View();
    }

    public IActionResult About()
    {
      ViewBag.Title = "About Us";

      return View();
    }
  }
}

WebApplication3/Controllers/TvShowController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WebApplication3.Data;
using WebApplication3.Data.Entities;
using WebApplication3.Models;
using WebApplication3.Models.ViewModels;

namespace WebApplication3.Controllers
{
  public class TvShowController : Controller
  {
    private readonly ITvShowRepository repository;
    private readonly UserManager<ApplicationUser> userManager;

    public TvShowController(ITvShowRepository repository,
      UserManager<ApplicationUser> userManager)
    {
      this.repository = repository;
      this.userManager = userManager;
    }

    public IActionResult Index()
    {
      return View();
    }

    public IActionResult Search(string searchQuery)
    {
      var result = repository.SearchForTvShow(searchQuery).ToList();

      if (result != null)
        return View(result);

      return View(nameof(AppController.Index));
    }

    // För ajax anrop
    //[HttpGet]
    //public IActionResult Search(string searchQuery)
    //{
    //  var result = repository.SearchForTvShow(searchQuery);

    //  return PartialView("SearchResult", result);
    //}

    [HttpGet]
    [Authorize]
    public async Task<IActionResult> FollowedShows()
    {
      var tmp = HttpContext.User;
      var user = await userManager.GetUserAsync(tmp);
      // todo snygga till denna kod, inte dry..
      user.FollowedShowIds = repository.GetUsersFollowedShowIds(user.Id);
      List<TvShow> followedShows = new List<TvShow>();

      foreach (var show in user.FollowedShowIds)
        followedShows.Add(repository.GetShowAndEpisodeDetailsByTvMazeId(show.ShowId));

      FollowedShowsViewModel model = new FollowedShowsViewModel
      {
        User = user,
        FollowedShows = followedShows
      };

      return View(model);
    }

    [Authorize]
    public async Task<IActionResult> FollowShow(int tvShowId)
    {
      if (ModelState.IsValid)
      {
        if (this.User.Identity.IsAuthenticated)
        {
          var tmp = HttpContext.User;
          var user = await userManager.GetUserAsync(tmp);

          user.FollowedShowIds = repository.GetUsersFollowedShowIds(user.Id);

          TvShowId tvShowToFollowId = new TvShowId(tvShowId);

          if (user.FollowedShowIds == null)
            user.FollowedShowIds = new List<TvShowId>();

          #region dublettkontroll
          bool alreadyFollowing = false;
          foreach (var show in user.FollowedShowIds)
            if (show.ShowId == tvShowId)
              alreadyFollowing = true;

          if (!alreadyFollowing)
            user.FollowedShowIds.Add(tvShowToFollowId);
          #endregion

          repository.SaveAll();
        }
      }

      return View(nameof(AppController.Index));
    }

    [Authorize]
    public async Task<IActionResult> UnFollowShow(int tvShowId)
    {
      if (ModelState.IsValid)
      {
        if (this.User.Identity.IsAuthenticated)
        {
          var tmp = HttpContext.User;
          var user = await userManager.GetUserAsync(tmp);
          user.FollowedShowIds = repository.GetUsersFollowedShowIds(user.Id);
          TvShowId tvShowToUnfollowId = new TvShowId(tvShowId);

          bool alreadyFollowing = false;

          if (user.FollowedShowIds != null)
            foreach (var show in user.FollowedShowIds)
              if (show.ShowId == tvShowToUnfollowId.ShowId)
                alreadyFollowing = true;

          if (alreadyFollowing)
            user.FollowedShowIds.RemoveAll(x => x.ShowId == tvShowToUnfollowId.ShowId);

          repository.SaveAll();
        }
      }

      return View(nameof(AppController.Index));
    }

    [HttpGet]
    public IActionResult Details(int id)
    {
      var result = repository.GetShowAndEpisodeDetailsByTvMazeId(id);
      return View(result);
    }
  }

}

WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <title>FoShow: @ViewBag.Title</title>

  <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
  <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
  <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
  <div class="navbar navbar-inverse">
    <header class="container">
      <div class="navbar-header">
        <div class="navbar-brand"><i class="fa fa-tv"></i> FoShow!</div>
        <button class="navbar-toggle" data-toggle="collapse" data-target="#menu">&#9776;</button>
        <form asp-controller="TvShow" asp-action="Search" method="get" class="navbar-form">
          <input class="form-control" name="searchQuery" type="text" placeholder="Search for Tv Shows" />
          <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
        </form>
      </div>
      <div id="menu" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a asp-controller="App" asp-action="Index">Home</a></li>
          <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
          <li><a asp-controller="App" asp-action="About">About</a></li>
          <li>
          </li>
          @if (User.Identity.IsAuthenticated)
          {
            <li><a asp-controller="Account" asp-action="Logout">Logout</a></li>
          }
          else
          {
            <li><a asp-controller="Account" asp-action="Login">Login</a></li>
            <li><a asp-controller="Account" asp-action="Register">Register</a></li>
          }
        </ul>
      </div>
    </header>
  </div>

  <section class="container">
    <h2 class="text-center">@ViewBag.Title</h2>
    @RenderBody()
  </section>

  <footer class="container">
    <div class="text-center">Copyright 2017 FoShow</div>
  </footer>


  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
  <script src="~/js/index.js"></script>
  @RenderSection("scripts", false)
</body>
</html>